#cloud-config
packages:
  - nfs-kernel-server

runcmd:
  # NFS
  - mkdir -p /shared
  - chown ${admin_user} /shared
  - systemctl enable nfs-kernel-server
  - systemctl start nfs-kernel-server
  # Kubeadm  
  - echo "SUDO_UID=${admin_user} sudo -E /tmp/kubeadm-bootstrap/init-master.bash" >> /tmp/install.sh
  - su ${admin_user} -c "/tmp/install.sh"
  - kubeadm token create --print-join-command > /shared/kubeadm-join.bash

write_files:
  - path: /etc/exports
    content: |
      /shared  ${cidr}(rw,sync,no_root_squash,no_all_squash)
